name=MLX90641 Infrared Sensor Module
version=1.0.0
author=Eray Eroglu <eray.eroglu@boardoza.com>
maintainer=Boardoza <Boardoza.com>
sentence=Library for MLX90641 Infrared Sensor Module
paragraph=This library provides an easy-to-use API for interfacing with the MLX90641 infrared sensor module. It supports temperature readings, initialization, and error handling. Designed for Arduino and PlatformIO projects, it includes example sketches and minimal dependencies.
category=Sensor
url=https://github.com/Boardoza/MLX90641_Infrared_Sensor_Module
architectures=*